name: Build XCFramework

on:
  pull_request:
    types: [closed]
    branches: [ develop ]
  workflow_dispatch:
    branches: [ main, develop ]

jobs:
  xcframework:
    name: Build XCFramework
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ github.token }}    

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true
  
    - name: Build XCFramework
      run: |
        bundle exec fastlane build_xcframework

    - name: Commit framework
      uses: EndBug/add-and-commit@v7
      with:
        add: 'framework'
        author_name: GithubAction
        author_email: p.prokopowicz1@gmail.com
        message: 'XCFramework built'

