name: Build XCFramework

on:
  push:
    branches: [ develop ]
    paths:
      - 'Sources/**'
  workflow_dispatch:
    branches: [ main, develop ]

jobs:
  xcframework:
    name: Build XCFramework
    runs-on: macos-latest

    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.CI_TOKEN }}
        ref: ${{ steps.extract_branch.outputs.branch }}

    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ github.token }}    

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true
  
    - name: Build XCFramework
      run: |
        bundle exec fastlane build_xcframework

    - name: Commit framework
      uses: EndBug/add-and-commit@v7
      with:
        add: 'framework'
        author_name: GithubAction
        author_email: p.prokopowicz1@gmail.com
        message: 'XCFramework built'
        branch: ${{ steps.extract_branch.outputs.branch }}

