name: Swift

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ouzi-dev/commit-status-updater@v1.0.7
    - name: Run tests
      run: swift test
