name: Tests

on:
  workflow_dispatch:
    branches: [ main, develop ]

jobs:
  test:
    name: Tests
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ github.token }}  

    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true

    - name: Run tests
      run: |
        bundle exec fastlane tests
